---
title: "Credit Card Customer Churn"
author: "Adogbeji Agberien"
date: "13/05/2021"
output: 
  html_document: 
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### NOTE: STILL WORKING!!! 


# Background 

Customer churn is the loss/turnover of a client. For this analysis, the goal is to predict/classify customers who will churn. We will begin by importing the necessary packages and performing some exploratory data analysis. 

```{r warning=F, message=F}
# Import and load packages
required_packages <- c("RColorBrewer", "cowplot", 
                       "lubridate", 
                       "Hmisc", "psych", "DataExplorer",
                       "tidyverse", "data.table", "knitr",
                       "precrec", "rpart.plot", "smotefamily",
                       "mlr3", "mlr3learners", "mlr3viz", 
                       "mlr3filters", "mlr3pipelines", "mlr3tuning")

packageCheck <- lapply(required_packages, FUN = function(x) {
  if(!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})
```

```{r echo=F}
# Import the data 
bank_churn <- fread("C:/Users/diji_/Desktop/Data Science/Projects/Bank Churn/BankChurners.csv")
bank_churn <- bank_churn[, c(-22, -23)]
```

```{r}
# Select the character variables to be converted factors
character_variables <- c("Attrition_Flag", "Gender", "Education_Level", "Marital_Status", "Income_Category", "Card_Category")

# Convert the character variables to factors
bank_churn[, (character_variables) := lapply(.SD, factor), .SDcols = character_variables]

# Select the integersvariables to be converted to numeric
numeric_variables <- c("Customer_Age", "Total_Revolving_Bal", "Total_Trans_Amt")

# Convert some integers to numeric
bank_churn[, (numeric_variables) := lapply(.SD, as.numeric), .SDcols = numeric_variables]

# Verify that classes have been appropriately set 
lapply(bank_churn, class)
```

```{r}
# Create the task 
task <- TaskClassif$new(id = "BankChurn", backend = bank_churn, target = "Attrition_Flag")
print(task)
```

```{r}
# Set CLIENTNUM as an identifier 
task$set_col_roles("CLIENTNUM", roles = "name")
```

```{r}
# Explore the task 
as.data.table(task$col_info)
task$col_roles
table(task$truth()) # Class imbalance with Attrited customers being 1/5 less than Existing customers 
task$positive
Hmisc::describe(as.data.table(task))
```

```{r}
# Split the task into training and test sets 
train_set <- sample(task$nrow, 0.8*task$nrow)
test_set <- setdiff(seq_len(task$nrow), train_set)
```

```{r}
# Create learner 
learner_dt <- lrn("classif.rpart")
```

```{r}
# DECISION TREE MODEL; ORIGINAL DATA 
# Do nothing sampler
doing_nothing <- po("nop", id = "nop")

# Create ML graph for undersampler
doing_nothing_sampler <- doing_nothing %>>% 
  learner_dt
 
# Create a graph learner for undersampler
graph_learner_doing_nothing_sampler <- GraphLearner$new(doing_nothing_sampler)

# Train the undersampler decision tree model
graph_learner_doing_nothing_sampler$train(task, train_set)

# Show the state of the learner
graph_learner_doing_nothing_sampler$state
```

```{r}
# Visualize undersampler decision tree model
rpart.plot(graph_learner_doing_nothing_sampler$state$model$classif.rpart$model, cex = 0.6)
```

```{r}
# Make predictions on the test set 
prediction_dt <- graph_learner_doing_nothing_sampler$predict(task, test_set)

# Show confusion matrix
prediction_dt$confusion

# Print sensitivity
prediction_dt$score(msr("classif.sensitivity"))
prediction_dt$score(msr("classif.ce"))
prediction_dt$score(msr("classif.fbeta"))

# DECISION TREE MODEL; UNDERSAMPLER
# Create an undersampler 
undersampler <- po("classbalancing", ratio = 1/5, reference = "major", adjust = "major", shuffle = F, id = "undersampler")

# Create ML graph for undersampler
dt_undersampler <- undersampler %>>% 
  learner_dt

# Create a graph learner for undersampler
graph_learner_undersampler <- GraphLearner$new(dt_undersampler)

# Train the undersampler decision tree model
graph_learner_undersampler$train(task, train_set)

# Show the state of the learner
graph_learner_undersampler$state

# Visualize undersampler decision tree model
rpart.plot(graph_learner_undersampler$state$model$classif.rpart$model, cex = 0.6)

# Make predictions on the test set 
undersampler_prediction_dt <- graph_learner_undersampler$predict(task, test_set)

# Show confusion matrix
undersampler_prediction_dt$confusion

# Print sensitivity
undersampler_prediction_dt$score(msr("classif.sensitivity"))
undersampler_prediction_dt$score(msr("classif.ce"))
undersampler_prediction_dt$score(msr("classif.fbeta"))

# DECISION TREE MODEL; OVERSAMPLER 
# Create an oversampler 
oversampler = po("classbalancing", ratio = 5, reference = "minor", adjust = "minor", shuffle = F, id = "oversampler")

# Oversampler 
dt_oversampler <- oversampler %>>% 
  learner_dt

# Create a graph learner for oversampler
graph_learner_oversampler <- GraphLearner$new(dt_oversampler)

# Train the oversampler decision tree model
graph_learner_oversampler$train(task, train_set)

# Show the state of the learner
graph_learner_oversampler$state
```

```{r}
# Visualize oversampler decision tree model
rpart.plot(graph_learner_oversampler$state$model$classif.rpart$model, cex = 0.6)
```

```{r}
# Make predictions on the test set 
oversampler_prediction_dt <- graph_learner_oversampler$predict(task, test_set)

oversampler_prediction_dt$confusion
oversampler_prediction_dt$score(msr("classif.sensitivity"))
oversampler_prediction_dt$score(msr("classif.ce"))
oversampler_prediction_dt$score(msr("classif.fbeta"))
```

```{r warning = F, message = F}
# Benchmarking 
dt_benchmark <- benchmark_grid(tasks = task,
                               learners = c(graph_learner_doing_nothing_sampler,
                                            graph_learner_undersampler, 
                                            graph_learner_oversampler), 
                               resamplings = rsmp("cv", folds = 2))

dt_bm_results <- benchmark(dt_benchmark)

as.data.table(
  dt_bm_results$aggregate(
    c(msr("classif.ce"),
      msr("classif.sensitivity"),
      msr("classif.fbeta"))))[, c(
        "learner_id", "classif.ce", "classif.sensitivity", "classif.fbeta")]
```
